Hero/urls.py
from django.contrib import admin
from django.urls import path

from Hero_app import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.MainView.as_view(), name='main'),

    path('create_char', views.CharCreateView.as_view(), name='char-create'),
    path('char', views.CharView.as_view(), name='char'),

    path('add_activity_type', views.AddActivityTypeView.as_view(), name='add-activity-type'),
    path('activity_types', views.ActivityTypesView.as_view(), name='activity-types'),

    path('add_activity', views.AddActivityView.as_view(), name='add-activity'),
    path('activity', views.ActivityView.as_view(), name='activities'),

    path('add_day', views.AddDayView.as_view(), name='add-day'),
    path('day', views.DayView.as_view(), name='day'),
    path('edit_day/<int:pk>/', views.EditDayView.as_view(), name='edit-day'),

    path('char_page', views.CharPageView.as_view(), name='char-page'),
]

Hero_app/models.py
from django.core.exceptions import ObjectDoesNotExist
from django.db import models
from django.db.models import Avg
from django.db.models.signals import post_save
from django.dispatch import receiver

# Create your models here.


level_of_fatigue = [
    (1, 'Very Low'),
    (2, 'Low'),
    (3, 'Moderate'),
    (4, 'High'),
    (5, 'Very High'),
]
mood_level = [
    (1, 'Unmotivated'),
    (2, 'Neutral'),
    (3, 'Ready'),
    (4, 'Motivated'),
    (5, 'Eager'),
]


class ActivityType(models.Model):
    name = models.CharField()
    type = models.CharField(null=True, blank=True)
    body_party = models.CharField(null=True, blank=True)

    def __str__(self):
        return self.name


class Activity(models.Model):
    name = models.CharField()
    date = models.DateField(null=True, blank=True)
    activity_type = models.ForeignKey(ActivityType, on_delete=models.CASCADE, )
    fatigue = models.IntegerField(choices=level_of_fatigue, null=True, blank=True)
    duration = models.TimeField(null=True, blank=True)
    notes = models.TextField(null=True, blank=True)

    def __str__(self):
        return self.name


@receiver(post_save, sender=Activity)
def create_day_with_activity(sender, instance, created, **kwargs):
    if created:
        try:
            day = Day.objects.get(date=instance.date)
            day.activity.add(instance)
        except ObjectDoesNotExist:
            new_day = Day.objects.create(date=instance.date)
            new_day.activity.add(instance)


class Day(models.Model):
    date = models.DateField(unique=True)
    mood = models.IntegerField(choices=mood_level, null=True, blank=True)
    fatigue = models.IntegerField(choices=level_of_fatigue, null=True, blank=True)
    note = models.TextField(null=True, blank=True)
    activity = models.ManyToManyField(Activity, null=True, blank=True)


class Char(models.Model):
    name = models.CharField()
    height = models.DecimalField(max_digits=5, decimal_places=2)
    weight = models.DecimalField(max_digits=5, decimal_places=2)
    bmi = models.DecimalField(max_digits=4, decimal_places=2, null=True, blank=True)
    age = models.IntegerField()
    fat_percent = models.IntegerField(null=True, blank=True)
    days = models.ForeignKey(Day, on_delete=models.CASCADE, null=True)

    def save(self, *args, **kwargs):
        if self.pk:
            old_char = Char.objects.get(pk=self.pk)
            if old_char.height != self.height or old_char.weight != self.weight:
                self.bmi = float(self.weight) / (float(self.height) / 100) ** 2
        else:
            self.bmi = float(self.weight) / (float(self.height) / 100) ** 2
        super(Char, self).save(*args, **kwargs)


@receiver(post_save, sender=Char)
def add_weight_in(sender, instance, created, **kwargs):
    if created:
        WeightIn.objects.create(weight=instance.weight)


class WeightIn(models.Model):
    char = models.ForeignKey(Char, on_delete=models.CASCADE)
    weight = models.DecimalField(max_digits=5, decimal_places=2)
    create_date = models.DateField(auto_now_add=True)


@receiver(post_save, sender=WeightIn)
def update_weight(sender, instance, created, **kwargs):
    if created:
        instance.char.weight = instance.weight
        instance.char.save()

templates/activity_list.html
{% extends 'main.html' %}
{% block content %}


<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
{% for activity in activities %}
<div>
    <div>{{ activity.name }}</div>
    <div>{{ activity.date }}</div>
    <div>{{ activity.get_fatigue_display }}</div>
    <div>{{ activity.notes }}</div>
</div>
{% endfor %} 
</body>
</html>


{% endblock %}

templates/activity_types.html
{% extends 'main.html' %}
{% block content %}
    <!doctype html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport"
              content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">
        <title>Document</title>
    </head>
    <body>
    {% for type in activity_types %}
        <div>{{ type.name }}</div>
        <div>{{ type.type }}</div>
        <div>{{ type.body_party }}</div>
    {% endfor %}
    </body>
    </html>
{% endblock %}

templates/add_activity.html
{% extends 'main.html' %}
{% block content %}

<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>

<form method="POST">
    {% csrf_token %}
{{ form }}
    <input type="submit">
    </form>

</body>
</html>


{% endblock %}

templates/add_activity_type.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
<form method="POST">
    {% csrf_token %}
{{ form }}
    <input type="submit">
    </form>
</body>
</html>

templates/add_day.html
{% extends 'main.html' %}
{% block content %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Create your character</title>
</head>

<body>

<form method="POST">
    {% csrf_token %}
{{ form }}
    <input type="submit">
    </form>
</body>
</html>


{% endblock %}

templates/char.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Create your character</title>
</head>

<body>

<form method="POST">
    {% csrf_token %}
{{ form }}
    <input type="submit">
    </form>
</body>
</html>

templates/char_page.html
{% extends 'main.html' %}
{% block content %}
    <!doctype html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport"
              content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">
        <title>Document</title>
        {% load static %}
        <script src="{% static 'javascripts/char_page.js' %}"></script>

    </head>
    <body>

    <div>{{ char.name }}</div>
    {{ char.bmi }}

    <div id="wight_add">
        <form method="POST">
            {% csrf_token %}
            weight in:
            <input type="number" step="any" name='weight' id="weight">
            <input type="submit" name="weight_in" id="weight_in" value="Add">
        </form>
    </div>


    <div class=" buttons_group">
        <button id="all_data_button">Show all data</button>
        <button id="month_summary_button">Show month data</button>
        <button id="week_summary_button">Show week data</button>
    </div>

    

    <div id="all_data" style="display: block">
        <h2>all workouts:</h2>
        <form method="GET">
            <a href="/char_page?week_data=true">show weeks</a>
           <a href="/char_page?week_previous=true">pervious week</a>
           <a href="/char_page?week_next=true">next week</a>
        </form>
    
        <div>
            <table>
                <tr>
                    {% for day in days %}
                        <th><a href={% url 'edit-day' pk=day.pk %}>{{ day.date }}</a></th>
                    {% endfor %}
                </tr>
                <tr>
                    {% for day in days %}
                        <td>
                            <table>
                                {% for activity in day.activity.all %}
                                    <tr>
                                        <td>{{ activity.name }}</td>
                                        <td>- {{ activity.duration.hour }}:{{ activity.duration.minute }}</td>
                                        <td>Ftg: {{ activity.fatigue }}</td>
                                    </tr>
                                {% endfor %}
                            </table>
                                <table>
{#                            <tr>#}
{#                                <td>{% load my_filters %}#}
{#                                    {% if daily_avg_fatigue|get:day.date %}#}
{#                                        avg daily ftg: {{ daily_avg_fatigue|get:day.date }}#}
{#                                    {% else %}#}
{#                                        -#}
{#                                    {% endif %}</td>#}
{#                            </tr>#}
                        </table>
                        </td>
                    {% endfor %}
                </tr>
            </table>
        </div>
        <ul>
            {% for activity, count in whole_activities %}
                <li>{{ activity }}: {{ count }}</li>
            {% endfor %}
            {% if avg_mood %}
                avg MOOD: {{ avg_mood }}
            {% endif %}
            <br>
            {% if avg_fatigue %}
                avg FATIGUE: {{ avg_fatigue }}
            {% endif %}
        </ul>
        <div class="chart">
            {% if all_data_chart %}
                <img src="data:image/png;base64, {{ all_data_chart|safe }}">
            {% endif %}

        </div>
    </div>


    <div id="month_summary" style="display: none">
        <h2>Month summary:</h2>
        <div>
            <table>
                <tr>
                    {% for day in month_summary %}
                        <th><a href={% url 'edit-day' pk=day.pk %}>{{ day.date }}</a></th>
                    {% endfor %}
                </tr>
                <tr>
                    {% for day in month_summary %}
                        <td>
                            <table>
                                {% for activity in day.activity.all %}
                                    <tr>
                                        <td>{{ activity.name }}</td>
                                        <td>- {{ activity.duration.hour }}:{{ activity.duration.minute }}</td>
                                        <td>Ftg: {{ activity.fatigue }}</td>
                                    </tr>
                                {% endfor %}
                            </table>
                                <table>
                            <tr>
                                <td>{% load my_filters %}
                                    {% if daily_avg_fatigue_for_month|get:day.date %}
                                        avg daily ftg: {{ daily_avg_fatigue_for_month|get:day.date }}
                                    {% else %}
                                        -
                                    {% endif %}</td>
                            </tr>
                        </table>
                        </td>
                
                    {% endfor %}
                </tr>
            </table>
        </div>
        <ul>
            {% for activity, count in month_activity %}
                <li>{{ activity }}: {{ count }}</li>
            {% endfor %}
            {% if avg_mood_month %}
                Month MOOD: {{ avg_mood_month }}
            {% endif %}
            <br>
            {% if avg_fatigue_month %}
                Month FATIGUE: {{ avg_fatigue_month }}
            {% endif %}
        </ul>

        <div class="chart">
            {% if monthly_chart %}
                <img src="data:image/png;base64, {{ monthly_chart|safe }}">
            {% endif %}

        </div>
    </div>
{#------------------ WEEK ----------------------------#}

    <div id="week_summary" style="display: block;">
        <h2>week summary:</h2>
    
        <div id="week_buttons">
            <button id ='week_data'>show weeks</button>
           <button id="week_summary_button">previous week data</button>
           <button id="week_summary_button">next week data</button>
    </div>
    
    
    
        <div>
            <table>
                <tr>
                    {% for day in week_summary %}
                        <th><a href={% url 'edit-day' pk=day.pk %}>{{ day.date }}</a><br>DAY Fatigure: {{ day.fatigue }}
                        </th>

                    {% endfor %}
                </tr>
                <tr>
                    {% for day in week_summary %}


                        <td>
                            <table>
                                {% for activity in day.activity.all %}
                                    <tr>
                                        <td>{{ activity.name }}</td>
                                        <td>- {{ activity.duration.hour }}:{{ activity.duration.minute }}</td>
                                        <td>{{ activity.activity_type }}</td>
                                        <td>Ftg: {{ activity.fatigue }}</td>


                                    </tr>

                                {% endfor %}
                            </table>
                            <table>
                                <tr>
                                    <td>{% load my_filters %}
                                        {% if daily_avg_fatigue_for_week|get:day.date %}
                                            avg daily ftg: {{ daily_avg_fatigue_for_week|get:day.date }}
                                        {% else %}
                                            -
                                        {% endif %}</td>
                                </tr>
                            </table>
                        </td>

                    {% endfor %}

                </tr>
            </table>
        </div>

        <ul>
            {% for activity, count in week_activity %}
                <li>{{ activity }}: {{ count }}</li>
            {% endfor %}
            {% if avg_mood_week %}
                Week MOOD: {{ avg_mood_week }}
            {% endif %}
            <br>
            {% if avg_fatigue_week %}
                Week FATIGUE: {{ avg_fatigue_week }}
            {% endif %}
        </ul>

        <div class="chart">
            {% if weekly_chart %}
                <img src="data:image/png;base64, {{ weekly_chart|safe }}">
            {% endif %}

        </div>
    </div>


    
    
    </body>
    </html>



{% endblock %}

templates/charview.html
{% extends 'main.html' %}
{% block content %}

<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
{% for char in character %}
    <div>NAAME:{{ char.name }}</div>
    <div>BMI:{{ char.bmi }}</div>    
    <div>AGE:{{ char.age }}</div>
{% endfor %}
</body>
</html>

{% endblock %}

templates/day.html
{% extends 'main.html' %}
{% block content %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
{%  for i in day %}
<div>{{ i.date }}</div>
    {% if i.activity.all  %}
        {% for activity in i.activity.all  %}
            <div>{{ activity.name }}</div>
            {% endfor %}
    {% endif %}
{% endfor %}
</body>
</html>

{% endblock %}

templates/edit_day.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
    <h1>Edit Day</h1>
    <form method="POST">
        {% csrf_token %}
        {{ form}}
        <input type="submit" value="Save">
    </form>
</body>
</html>

templates/index.html
{% extends 'main.html' %}
{% block content %}


<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>


INDEX
</body>
</html>



{% endblock %}

templates/main.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>main</title>
</head>
<body>
<a href="{% url 'char-page' %}">Char page</a>
<a href="{% url 'char-create' %}">Char create</a>
<a href="{% url 'char' %}">Char</a>
<a href="{% url 'add-activity-type' %}">Add ActivType</a>
<a href="{% url 'activity-types' %}">ActivTypes</a>
<a href="{% url 'add-activity' %}">Add Activity</a>
<a href="{% url 'activities' %}">Activities list</a>
<a href="{% url 'add-day' %}">Add Day</a>
<a href="{% url 'day' %}">Day</a>

{% block content %}
{% endblock %}

</body>
</html>